"""empty message

Revision ID: 29ce1810b228
Revises: 
Create Date: 2023-12-11 19:59:29.420618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ce1810b228'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_part', sa.String(), nullable=False),
    sa.Column('abbreviation_character', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation_character'),
    sa.UniqueConstraint('body_part')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_ang', sa.String(length=120), nullable=True),
    sa.Column('main_body_part_id', sa.Integer(), nullable=False),
    sa.Column('another_body_part', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media', sa.LargeBinary(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['another_body_part'], ['body_parts.id'], ),
    sa.ForeignKeyConstraint(['main_body_part_id'], ['body_parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name_ang')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises')
    op.drop_table('body_parts')
    # ### end Alembic commands ###
